services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - sqlserver
    ports:
      - "8000:8000"
    environment:
      DB_HOST: sqlserver
      DB_USER: sa
      DB_PASSWORD: "YourStrong!Passw0rd"
      DB_NAME: gestao_infra

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
